---
title: "GA_analysis"
author: "Michael Breshock"
date: "6/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(googleAnalyticsR)
```

```{r}

ocs_property_id = 256923228
yesterday = Sys.Date() - 1
ses_wk_ctg = google_analytics(ocs_property_id,
          date_range = c("2021-01-01", yesterday),
          metrics = c("sessions"),
          dimensions = c("week", "deviceCategory"))
head(ses_wk_ctg)
```

```{r}
# ocsmeta = ga_meta("data", propertyId = 256923228)
ses_wk_ctg = ga_data(ocs_property_id,
          date_range = c("2021-01-01", "yesterday"),
          metrics = c("sessions"),
          dimensions = c("week", "deviceCategory"))
ses_wk_ctg
```

```{r}
users_wk = ga_data(ocs_property_id,
          date_range = c("2021-01-01", "yesterday"),
          metrics = c("totalUsers", "newUsers", "eventCount",
                      "active7DayUsers"),
          dimensions = c("week"))
users_wk
```


what does time elapsed in google analytics mean? 
time the page is open on the laptop? or time spent actively engaging with the page? 

cool figure to make: # of events (or users) per day (events y axis, days x axis)
have a timeline of project development along the x-axis to view if website traffic was changed at all by project developments. 
