---
title: "OCSdata_analysis"
author: "Michael Breshock"
date: "9/20/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(Visualize.CRAN.Downloads)
library(packageRank)
library(ggplot2)
library(tidyverse)
```

```{r}
# retrieve data
packageData <- retrievePckgData("OCSdata", "2021-03-01")
# select 1st element of the list
totalDownloads <- packageData[[1]]

# call the plotting fn, with default value of device --> PDF
staticPlots(totalDownloads)
interactivePlots(totalDownloads, nbrPlts = 1, mytitle = paste("OCSdata Package Download Counts"))
```

```{r}
downloads = cranDownloads(packages = "OCSdata", from = "2021-03-01", to = Sys.Date())
downloads = tibble(downloads$cranlogs.data) %>%
  mutate(day = as.numeric(c(1:length(date))))
downloads
```

```{r}
theme_set(theme_minimal() + theme(axis.text = element_text(size = 11, color = "black"),
                                  axis.title = element_text(size = 12, color = "black"),
                                  plot.title = element_text(hjust = .5))
          )
```

```{r}
p = ggplot(downloads, aes(x = day, y = count)) + geom_point(size = 2)

spline_down = as.data.frame(spline(downloads$day, downloads$count))

p + geom_line(spline_down, mapping = aes(x = x, y = y), 
                          color = "#4B9B81",
                          linetype = "dashed", size = 1) +
  labs(x = "Number of Days (since release)", y = "Number of Downloads", 
       title = "Number of Downloads per Day Since Release")

```

```{r}
ggplot(downloads, aes(x = day, y = cumulative)) + 
  geom_line(size = 2, color = "#4B9B81") +
    labs(x = "Number of Days (since release)", y = "Total Downloads", 
       title = "Cumulative Number of Downloads Since Release")
```

```{r}
theme_set(theme_linedraw() + 
            theme(axis.text = element_text(size = 11, 
                                           color = "black"),
                  axis.title = element_text(size = 12, 
                                            color = "black"),
                  plot.title = element_text(size = 14, 
                                            color = "black",
                                            hjust = .5))
          )
```

```{r interactive elements}
counts = c(88,43,40,5)
type = c("All", "Multiple Choice", "Fill in the Chunk", 
         "Fill in the Blank")

exercises = tibble(counts, type)

ggplot(exercises, aes(x = reorder(type, -counts), y = counts, fill = type)) +
  geom_col(color = "black") + scale_fill_viridis_d() +
  labs(x = "Exercise Type", y = "Count", title = "Number of Interactive Exercises Implemented to Case Studies") + 
  guides(fill = "none") + 
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5)) + 
  geom_text(aes(label = paste0(counts)), vjust = -.5) + ylim(0,100)
```



